# Generated by Django 4.1.4 on 2023-04-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0003_alter_act_setlist_url_alter_artist_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concert",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AddField(
            model_name="artist",
            name="image_url",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
